{
 "title": "DOCSIS",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Downstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DOCSIS - Downstream Correctable Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (channel) (rate(docsis_ds_err_corrected_count{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DOCSIS - Downstream Uncorrectable Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (channel) (rate(docsis_ds_err_uncorrected_count{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "DOCSIS - Upstream Frequency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "sum by (channel, symbolRate) (docsis_us_info_freq{})",
       "legendFormat": "Chanel {{channel}} - {{symbolRate}} baud"
      }
     ]
    },
    {
     "title": "DOCSIS - Upstream Channel Power Levels",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "sum by (channel, symbolRate) (docsis_us_info_power{})",
       "legendFormat": "Chanel {{channel}} - {{symbolRate}} baud"
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "DOCSIS - Gateway Info",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "docsis_gateway_info{}",
       "legendFormat": "Gateway {{defaultGateway}} - External Address {{globalAddress}} - Mac Address {{ macAddress }}"
      }
     ]
    },
    {
     "title": "DOCSIS - Service Data Rates",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (direction, serviceFlowId) (docsis_service_flow_traffic_rate_max{})",
       "legendFormat": "{{direction}} - {{serviceFlowId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "DOCSIS - REST Server status codes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (statuscode) (rate(docsis_http_server_err_total{}[5m]))",
       "legendFormat": "http/{{statuscode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Python Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Python Stats",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=\"docsis_exporter\"}",
       "legendFormat": "VM - Allocated"
      },
      {
       "expr": "process_resident_memory_bytes{job=\"docsis_exporter\"}",
       "legendFormat": "VM - Resident"
      }
     ]
    }
   ]
  }
 ]
}